from .base import BaseAgent
from typing import Any, Dict


class Architect(BaseAgent):
    """
    Architect Agent

    Responsible for:
    - Receiving high-level objectives
    - Decomposing objectives into actionable steps
    - Producing a strategic plan for execution
    """

    def execute(self, objective: str) -> Dict[str, Any]:
        """
        Entry point for Architect execution.
        Returns a plan dictionary.
        """

        self.record({"input_objective": objective})

        # -------------------------
        # Step 1: Decompose objective
        # -------------------------
        plan_steps = self._decompose(objective)

        # -------------------------
        # Step 2: Annotate plan with reasoning
        # -------------------------
        plan = {
            "objective": objective,
            "steps": plan_steps,
            "notes": f"Generated by Architect agent using system prompt."
        }

        self.record({"plan": plan})

        return plan

    # -------------------------
    # INTERNAL LOGIC
    # -------------------------

    def _decompose(self, objective: str) -> list[str]:
        """
        Decompose objective into step-by-step plan.
        This is currently a placeholder; eventually will integrate
        LLM reasoning or custom logic.
        """

        # Simple mock decomposition for demonstration
        steps = [
            f"Analyze the objective: '{objective}'",
            "Break it into core components",
            "Identify dependencies and requirements",
            "Define execution phases",
            "Produce structured plan for downstream agents"
        ]

        return steps
